### ISSUE TITLE
Create Docker Package

### ISSUE THREAD

**Issue by Hassiopeia** [deepcoder/bluetooth-temperature-sensors#3]
It would be great if this was bundled as a Docker package, making it easily deployable. This is just an enhancement request I suppose. :-) Thanks for the great work. I use it to monitor my greenhouse each Spring!

**Comment by deepcoder** [comment]
I will see if I can give a docker package a try. But honestly, one of the reason went this route of a kind of bare metal rpi was that docker adds complexity that seemed to cause a lot of the other folks solutions to this problem to fail. This and the difficulty of the python libraries to talk to linux bluetooth stably. 

I want to work on restructuring the app next to allow better control of how often it sends MQTT packets. Right now due to the architecture of the app, it can send a lot of noise packets, especially for type 4 BLE sensors.

Thanks for trying it and your feedback.

Hope you get some success with it. It has been a solid add to my HA system.

**Comment by Hassiopeia** [comment]
That's understandable. This can be closed if you like. :-)
